{{- range $name, $priority := .Values.priorityClasses }}
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ $name }}
  labels:
    heritage: {{ $.Release.Service }}
    release: {{ $.Release.Name }}
value: {{ $priority }}
globalDefault: false
{{- end }}
