projectName: binderhub-288415

binderhub:
  enabled: false
  config:
    BinderHub:
      pod_quota: 20
      hub_url: https://hub.gke2.staging.mybinder.org
      badge_base_url: https://staging.mybinder.org
      image_prefix: gcr.io/binderhub-288415/r2d-staging-g5b5b759-
      sticky_builds: true
      build_memory_limit: "2G"
  extraEnv:
    EVENT_LOG_NAME: "binderhub-staging-events-text"

  resources:
    requests:
      cpu: 0.25
      memory: 512Mi

  hpa:
    enabled: true
    maxReplicas: 3
    minReplicas: 1
    targetCPU: 50 # 50% of cpu request, so 0.125 CPU

  dind:
    resources:
      requests:
        cpu: "0"
        memory: 1Gi
      limits:
        cpu: "1"
        memory: 2.5Gi

  ingress:
    hosts:
      - gke.staging.mybinder.org
      - gke2.staging.mybinder.org

  jupyterhub:
    hub:
      resources:
        requests:
          memory: 512Mi
          cpu: null
    singleuser:
      memory:
        guarantee: 256M
        limit: 256M
      cpu:
        guarantee: 0.1
        limit: 0.5
    ingress:
      hosts:
        - hub.gke.staging.mybinder.org
        - hub.gke2.staging.mybinder.org
      tls:
        - secretName: kubelego-tls-jupyterhub-staging
          hosts:
            - hub.gke.staging.mybinder.org
            - hub.gke2.staging.mybinder.org
    scheduling:
      userPlaceholder:
        replicas: 2

grafana:
  ingress:
    hosts:
      - grafana.staging.mybinder.org
      - grafana.gke2.staging.mybinder.org
    tls:
      - hosts:
          - grafana.staging.mybinder.org
          - grafana.gke2.staging.mybinder.org
        secretName: kubelego-tls-grafana
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: prometheus
          orgId: 1
          type: prometheus
          url: https://prometheus.staging.mybinder.org
          access: direct
          isDefault: true
          editable: false
  persistence:
    storageClassName: standard

prometheus:
  server:
    ingress:
      hosts:
        - prometheus.staging.mybinder.org
        - prometheus.gke2.staging.mybinder.org
      tls:
        - hosts:
            - prometheus.staging.mybinder.org
            - prometheus.gke2.staging.mybinder.org
          secretName: kubelego-tls-prometheus

ingress-nginx:
  controller:
    service:
      loadBalancerIP: 35.222.35.25

static:
  ingress:
    hosts:
      - static.staging.mybinder.org
      - static.gke2.staging.mybinder.org

redirector:
  enabled: true
  redirects:
    - type: host
      host:
        from: docs.staging.mybinder.org
        to: mybinder.readthedocs.io

matomo:
  enabled: true
  db:
    instanceName: binderhub-288415:us-central1:matomo-staging
  trustedHosts:
    - staging.mybinder.org
    - gke2.staging.mybinder.org
  ingress:
    hosts:
      - staging.mybinder.org
      - gke2.staging.mybinder.org

analyticsPublisher:
  enabled: true
  project: binderhub-288415
  destinationBucket: binder-staging-events-archive
  events:
    logName: binderhub-staging-events-text
    sourceBucket: binder-staging-events-raw-export

  # TODO: copy to values
  cloudCosts:
    sourceBucket: binder-billing-archive

gcsProxy:
  enabled: true
  buckets:
    - name: binder-staging-events-archive
      host: archive.analytics.gke2.staging.mybinder.org
    - name: binder-staging-events-archive
      host: archive.analytics.staging.mybinder.org

federationRedirect:
  host: staging.mybinder.org
  enabled: true
  hosts:
    gke:
      url: https://gke2.staging.mybinder.org
      weight: 4
      health: https://gke2.staging.mybinder.org/health
      versions: https://gke2.staging.mybinder.org/versions
    # unset the rest of the federation
    gesis:
      weight: 0
