{{- if .Values.awsEcrRegistryCleaner.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.awsEcrRegistryCleaner.serviceAccount.name }}
  labels:
    {{- include "binderhub-container-registry-helper.labels" . | nindent 4 }}
  {{- with .Values.awsEcrRegistryCleaner.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
