{{- if .Values.matomo.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matomo
  labels:
    app: matomo
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: matomo
spec:
  replicas: {{ .Values.matomo.replicas }}
  selector:
    matchLabels:
      app: matomo
      release: {{ .Release.Name }}
      component: matomo
  template:
    metadata:
      annotations:
        checksum/matomo-config: {{ include (print $.Template.BasePath "/matomo/configmap.yaml") . | sha256sum }}
        checksum/nginx-config: {{ include (print $.Template.BasePath "/matomo/nginx-configmap.yaml") . | sha256sum }}
      labels:
        app: matomo
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
        component: matomo
    spec:
      automountServiceAccountToken: false
      nodeSelector: {{ toJson .Values.matomo.nodeSelector }}
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
      - name: matomo-config
        configMap:
          name: matomo-config
      - name: matomo-nginx-config
        configMap:
          name: matomo-nginx-config
      - name: matomo-config-rw
        emptyDir: {}
      initContainers:
      - name: matomo-config-cp
        image: alpine:3.6
        command:
          - /bin/sh
        args:
          - -c
          - cp /etc/matomo-config/* /etc/matomo-config-rw/
        volumeMounts:
          - name: matomo-config
            mountPath: /etc/matomo-config
          - name: matomo-config-rw
            mountPath: /etc/matomo-config-rw
      containers:
      - name: matomo
        image: matomo:3.14.1-apache
        volumeMounts:
          - name: matomo-config-rw
            mountPath: /var/www/html/config/
        {{- with .Values.matomo.resources }}
        resources:
          {{- . | toYaml | nindent 10 }}
        {{- end }}
      - name: nginx
        image: nginx:1.15
        ports:
        - containerPort: 9000
        volumeMounts:
          - mountPath: /etc/nginx/conf.d/
            name: matomo-nginx-config
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command:
          - /cloud_sql_proxy
          - -instances={{ .Values.matomo.db.instanceName }}=tcp:3306
          - -credential_file=/secrets/cloudsql/credentials.json
        securityContext:
          runAsUser: 2  # non-root user
          allowPrivilegeEscalation: false
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
{{- end }}
