name: 'GESIS update dispatcher'

on:
  push:
    branches:
      - main

jobs:
  update-gesis:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatcher
        if: github.repository == 'jupyterhub/mybinder.org-deploy'
        env:
          GESIS_TOKEN: ${{ secrets.GESIS_TOKEN }}
        run: |
          curl -X POST \
          -F token=${GESIS_TOKEN} \
          -F ref=main \
          https://git.gesis.org/api/v4/projects/ilcm%2Forc2-upgrade-bot/trigger/pipeline
